name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Python tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
      - name: Run pytest
        run: |
          source .venv/bin/activate
          pytest --maxfail=1

  docker-smoke:
    name: Docker smoke test
    runs-on: ubuntu-latest
    needs: test
    if: env.DOCKER_SMOKE == 'true'
    steps:
      - uses: actions/checkout@v4
      - name: Start compose
        run: |
          docker compose up -d
          sleep 5
      - name: Smoke test /items
        run: |
          curl --retry 5 --retry-delay 1 --fail http://localhost:8000/items
      - name: Tear down
        run: |
          docker compose down
